### ISSUE TITLE
ValueError if signatureanalyzer is used with Indels

### ISSUE THREAD

**Issue by MaxiDoe** [getzlab/SignatureAnalyzer#39]
Dear getzlab, 

I am using signatureanalyzer to compare the calculated mutational signatures from my samples with a database like cosmic. 
If I am using cosmic3 or cosmic3_exome on SNPs everything works fine. But the moment I use cosmic3_ID for my detected Indels I encounter a ValueError as follows:

I've installed and tried signatureanalyzer through pip3, cloned the github repo, and pulled the docker but all ended up with the same error.

My Commandline Call: 

signatureanalyzer -n 10 --cosmic cosmic3_ID --hg_build hg19.2bit --objective poisson --max_iter 30000 sample_1_indels.maf

The Error is the following: 

Traceback (most recent call last):
  File "/home/maxid/miniconda3/bin/signatureanalyzer", line 8, in <module>
    sys.exit(main())
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/signatureanalyzer/__main__.py", line 179, in main
    run_maf(
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/signatureanalyzer/signatureanalyzer.py", line 84, in run_maf
    maf, spectra = get_spectra_from_maf(
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/signatureanalyzer/spectra.py", line 262, in get_spectra_from_maf
    spectra.loc[c] = 0
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1724, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/home/maxid/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 2012, in _setitem_with_indexer_missing
    raise ValueError("cannot set a frame with no defined columns")
ValueError: cannot set a frame with no defined columns

I put the "sample_1_indels.maf" in the attachment with which I encountered the error in all tries.

[sample_1_indels.zip](https://github.com/getzlab/getzlab-SignatureAnalyzer/files/7889659/sample_1_indels.zip)

If you need anything else, let me know. 

Regards, 
Maximilian Dörrbecker

**Comment by yoakiyama** [comment]
Hi @MaxiDoe. First thing I see is that your MAF is formatted in an non-standard manner. Typically, we see a dash '-' in Reference_Allele or Tumor_Seq_Allele2 depending on whether the mutation is an insertion or deletion. This is the way VCF to MAF software annotates indels (Oncotator or Funcotator). When SignatureAnalyzer subsets for indel mutations, it does so by running `maf = maf.loc[(maf['Reference_Allele'] == '-') ^ (maf['Tumor_Seq_Allele2'] == '-')]` In your case, this would be an empty dataframe. Please try running your VCF through a MAF annotator or reformat your MAF so that it is compatible. Thanks 

Best regards,
Yo Akiyama
