### ISSUE TITLE
TypeError: DataFrame.dropna()

### ISSUE THREAD

**Issue by sunyihong** [getzlab/SignatureAnalyzer#50]
Hello, I got the problem when using below command:
 signatureanalyzer test.maf -n 10 --objective poisson --hg_build ${hg_ref}

Here is the error:
Traceback (most recent call last):
  File "/opt/service/miniconda3/envs/signa_env/bin/signatureanalyzer", line 33, in <module>
    sys.exit(load_entry_point('signatureanalyzer', 'console_scripts', 'signatureanalyzer')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/signatureanalyzer/getzlab-SignatureAnalyzer/signatureanalyzer/__main__.py", line 195, in main
    run_maf(
  File "/software/signatureanalyzer/getzlab-SignatureAnalyzer/signatureanalyzer/signatureanalyzer.py", line 82, in run_maf
    reference_df, reference_index = load_reference_signatures(reference)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/signatureanalyzer/getzlab-SignatureAnalyzer/signatureanalyzer/utils.py", line 223, in load_reference_signatures
    reference = pd.read_csv(pkg_resources.resource_filename('signatureanalyzer', 'ref/cosmic_v2/sa_cosmic2.tsv'), sep='\t').dropna(1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFrame.dropna() takes 1 positional argument but 2 were given

Thank you!

**Comment by sunyihong** [comment]
it works! Thank you
